.PHONY: clean All

All:
	@echo "----------Building project:[ PlanesTable - Debug ]----------"
	@"$(MAKE)" -f  "PlanesTable.mk"
clean:
	@echo "----------Cleaning project:[ PlanesTable - Debug ]----------"
	@"$(MAKE)" -f  "PlanesTable.mk" clean
